name: PR Verify

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
      - name: Increase fs.aio-max-nr limit
        run: |
          echo "Current fs.aio-max-nr value:"
          cat /proc/sys/fs/aio-max-nr
          sudo sysctl -w fs.aio-max-nr=1048576
          echo "New fs.aio-max-nr value:"
          cat /proc/sys/fs/aio-max-nr
      - name: Maven verify
        run: mvn -B verify

