name: PR Verify

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - kafka_provider: "confluent"
            kafka_version: "8.0.0"
            kafka_connect_mode: "distributed"
            scylla_version: "6.2"
          - kafka_provider: "confluent"
            kafka_version: "7.9.2"
            kafka_connect_mode: "distributed"
            scylla_version: "6.2"
          - kafka_provider: "confluent"
            kafka_version: "7.8.3"
            kafka_connect_mode: "distributed"
            scylla_version: "6.2"
          - kafka_provider: "confluent"
            kafka_version: "7.7.4"
            kafka_connect_mode: "distributed"
            scylla_version: "6.2"
          - kafka_provider: "confluent"
            kafka_version: "7.6.6"
            kafka_connect_mode: "distributed"
            scylla_version: "6.2"
          - kafka_provider: "confluent"
            kafka_version: "8.0.0"
            kafka_connect_mode: "standalone"
            scylla_version: "6.2"
          - kafka_provider: "apache"
            kafka_version: "4.0.0"
            kafka_connect_mode: "distributed"
            scylla_version: "6.2"
          - kafka_provider: "apache"
            kafka_version: "4.0.0"
            kafka_connect_mode: "standalone"
            scylla_version: "6.2"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Increase fs.aio-max-nr limit
        run: |
          echo "Current fs.aio-max-nr value:"
          cat /proc/sys/fs/aio-max-nr
          sudo sysctl -w fs.aio-max-nr=1048576
          echo "New fs.aio-max-nr value:"
          cat /proc/sys/fs/aio-max-nr

      - name: Maven verify
        run: mvn -B verify -Dit.kafka.provider=${{ matrix.kafka_provider }} -Dit.kafka.version=${{ matrix.kafka_version }} -Dit.kafka.connect.mode=${{ matrix.kafka_connect_mode }} -Dit.scylla.version=${{ matrix.scylla_version }}
