name: PR Verify

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run-integration-tests:
    uses: ./.github/workflows/callable/compatibility-test.yml
    secrets: inherit
